name: Flutter CI - Build and Test (Android)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17

      - name: 'Set Flutter 3.19.6'
        uses: subosito/flutter-action@v2
        with:
             flutter-version: 3.19.6 # Update with your desired Flutter version

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-cache-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-cache-

      - name: Get pub dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Test Flutter app
        run: flutter test

      - name: Build Android app (release mode)
        run: flutter build appbundle --release

      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: android-release-bundle
          path: build/app/outputs/flutter-apk/release/app.aab
